// <auto-generated />
using System;
using Jogos_Academicos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jogos_Academicos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260131202253_TornarGrupoIdOpcional")]
    partial class TornarGrupoIdOpcional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EquipeGrupo", b =>
                {
                    b.Property<int>("EquipesId")
                        .HasColumnType("int");

                    b.Property<int>("GruposId")
                        .HasColumnType("int");

                    b.HasKey("EquipesId", "GruposId");

                    b.HasIndex("GruposId");

                    b.ToTable("grupos_equipes", (string)null);
                });

            modelBuilder.Entity("EquipeUsuario", b =>
                {
                    b.Property<int>("AtletasId")
                        .HasColumnType("int");

                    b.Property<int>("EquipeId")
                        .HasColumnType("int");

                    b.HasKey("AtletasId", "EquipeId");

                    b.HasIndex("EquipeId");

                    b.ToTable("equipe_atleta", (string)null);
                });

            modelBuilder.Entity("Jogos_Academicos.Models.Campus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_campus");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("campus");
                });

            modelBuilder.Entity("Jogos_Academicos.Models.ClassificacaoGrupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Derrotas")
                        .HasColumnType("int");

                    b.Property<int>("Empates")
                        .HasColumnType("int");

                    b.Property<int>("EquipeId")
                        .HasColumnType("int");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.Property<int>("SaldoGols")
                        .HasColumnType("int");

                    b.Property<int>("Vitorias")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipeId");

                    b.HasIndex("GrupoId", "EquipeId")
                        .IsUnique();

                    b.ToTable("classificacao_grupo");
                });

            modelBuilder.Entity("Jogos_Academicos.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cursos");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampusId")
                        .HasColumnType("int")
                        .HasColumnName("fk_campus");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nivel");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CampusId");

                    b.ToTable("cursos");
                });

            modelBuilder.Entity("Jogos_Academicos.Models.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_equipe");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CursoId")
                        .HasColumnType("int")
                        .HasColumnName("fk_curso");

                    b.Property<int>("EsporteId")
                        .HasColumnType("int")
                        .HasColumnName("fk_esporte");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TecnicoId")
                        .HasColumnType("int")
                        .HasColumnName("fk_tecnico");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("EsporteId");

                    b.HasIndex("TecnicoId");

                    b.ToTable("equipes");
                });

            modelBuilder.Entity("Jogos_Academicos.Models.Esporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_esporte");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("esportes");
                });

            modelBuilder.Entity("Jogos_Academicos.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_eventos");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("EsporteId")
                        .HasColumnType("int")
                        .HasColumnName("fk_esporte");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nivel");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EsporteId");

                    b.ToTable("eventos");
                });

            modelBuilder.Entity("Jogos_Academicos.Models.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_grupo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventoId")
                        .HasColumnType("int")
                        .HasColumnName("fk_eventos");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("grupos");
                });

            modelBuilder.Entity("Jogos_Academicos.Models.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_jogo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArbitroId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipeAId")
                        .HasColumnType("int");

                    b.Property<int>("EquipeBId")
                        .HasColumnType("int");

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<int>("Fase")
                        .HasColumnType("int");

                    b.Property<bool>("Finalizado")
                        .HasColumnType("bit");

                    b.Property<int?>("GrupoId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroRodada")
                        .HasColumnType("int");

                    b.Property<int?>("PlacarA")
                        .HasColumnType("int");

                    b.Property<int?>("PlacarB")
                        .HasColumnType("int");

                    b.Property<bool>("WoA")
                        .HasColumnType("bit");

                    b.Property<bool>("WoB")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ArbitroId");

                    b.HasIndex("EquipeAId");

                    b.HasIndex("EquipeBId");

                    b.HasIndex("EventoId");

                    b.HasIndex("GrupoId");

                    b.ToTable("jogos");
                });

            modelBuilder.Entity("Jogos_Academicos.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("apelido");

                    b.Property<int?>("CursoId")
                        .HasColumnType("int")
                        .HasColumnName("fk_curso");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("email");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("matricula");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome_completo");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telefone");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo_usuario");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EquipeGrupo", b =>
                {
                    b.HasOne("Jogos_Academicos.Models.Equipe", null)
                        .WithMany()
                        .HasForeignKey("EquipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jogos_Academicos.Models.Grupo", null)
                        .WithMany()
                        .HasForeignKey("GruposId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EquipeUsuario", b =>
                {
                    b.HasOne("Jogos_Academicos.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AtletasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jogos_Academicos.Models.Equipe", null)
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jogos_Academicos.Models.ClassificacaoGrupo", b =>
                {
                    b.HasOne("Jogos_Academicos.Models.Equipe", "Equipe")
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Jogos_Academicos.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipe");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("Jogos_Academicos.Models.Curso", b =>
                {
                    b.HasOne("Jogos_Academicos.Models.Campus", "Campus")
                        .WithMany("Cursos")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("Jogos_Academicos.Models.Equipe", b =>
                {
                    b.HasOne("Jogos_Academicos.Models.Curso", "Curso")
                        .WithMany("Equipes")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Jogos_Academicos.Models.Esporte", "Esporte")
                        .WithMany("Equipes")
                        .HasForeignKey("EsporteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Jogos_Academicos.Models.Usuario", "Tecnico")
                        .WithMany()
                        .HasForeignKey("TecnicoId");

                    b.Navigation("Curso");

                    b.Navigation("Esporte");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("Jogos_Academicos.Models.Evento", b =>
                {
                    b.HasOne("Jogos_Academicos.Models.Esporte", "Esporte")
                        .WithMany("Eventos")
                        .HasForeignKey("EsporteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Esporte");
                });

            modelBuilder.Entity("Jogos_Academicos.Models.Grupo", b =>
                {
                    b.HasOne("Jogos_Academicos.Models.Evento", "Evento")
                        .WithMany("Grupos")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("Jogos_Academicos.Models.Jogo", b =>
                {
                    b.HasOne("Jogos_Academicos.Models.Usuario", "Arbitro")
                        .WithMany()
                        .HasForeignKey("ArbitroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Jogos_Academicos.Models.Equipe", "EquipeA")
                        .WithMany()
                        .HasForeignKey("EquipeAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Jogos_Academicos.Models.Equipe", "EquipeB")
                        .WithMany()
                        .HasForeignKey("EquipeBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Jogos_Academicos.Models.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Jogos_Academicos.Models.Grupo", "Grupo")
                        .WithMany("Jogos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Arbitro");

                    b.Navigation("EquipeA");

                    b.Navigation("EquipeB");

                    b.Navigation("Evento");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("Jogos_Academicos.Models.Usuario", b =>
                {
                    b.HasOne("Jogos_Academicos.Models.Curso", "Curso")
                        .WithMany("Atletas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("Jogos_Academicos.Models.Campus", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("Jogos_Academicos.Models.Curso", b =>
                {
                    b.Navigation("Atletas");

                    b.Navigation("Equipes");
                });

            modelBuilder.Entity("Jogos_Academicos.Models.Esporte", b =>
                {
                    b.Navigation("Equipes");

                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("Jogos_Academicos.Models.Evento", b =>
                {
                    b.Navigation("Grupos");
                });

            modelBuilder.Entity("Jogos_Academicos.Models.Grupo", b =>
                {
                    b.Navigation("Jogos");
                });
#pragma warning restore 612, 618
        }
    }
}
